[package]
name = "async"
version = "0.1.0"
authors = ["JustinZhang <schnell18@gmail.com>"]
edition = "2024"
license = "MIT"
description = """
async programming
"""

[dependencies]
tokio = { version = "1", features = ["full"]}
reqwest = { version = "0.13", features = ["json"] }
ureq = { version = "3", features = ["socks-proxy", "charset"] }
