[package]
name = "aes"
version = "0.1.0"
authors = ["JustinZhang <schnell18@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-crypto = "^0.2"
rustc-serialize = "^0.3"
rand = "0.7.2"
